import Head from 'next/head'
import { Container, Grid, Title, Text, Box, Stack, Image, Group, Space } from '@mantine/core'
import { SocialsComponent } from '@/components/social/socials'
import { Tooltip as ReactTooltip } from 'react-tooltip'
import { useEffect } from 'react';
import { SpotifyComponent } from '@/components/spotify/spotify';
import { StatusComponent } from '@/components/status/status';
import { Icon } from '@iconify/react';
import { Projects } from '@/components/project/project';


export default function Home() {

  return (
    <>
      <Head>
        <title>jakub.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container className='hero-section' size={'md'} w={'100vh'}>
        <Grid align={'center'}  py={'xl'}>
          <Grid.Col sm={12} lg={6}>

            <Stack spacing={'sm'}>
              <Title>Jakub Szturomski <StatusComponent/></Title>

              <Text fw={500}>Hi there 👋🏼 I’m Jakub, I’m <Text underline component='span'>21</Text> years old</Text>
              <Text fw={500}>self-taught software engineer and cybersec enthusiast</Text>

              <Group spacing={'sm'}>
                <SocialsComponent />
              </Group>
            </Stack>
          </Grid.Col>
          <Grid.Col sm={12} lg={6}>
            <Image
              width={300}
              radius="xl"
              src="avatar.jpg"
            />

            <Space h="xl" />
            <Text>📍 Location: Gdynia, Poland</Text>
          </Grid.Col>
        </Grid>
      </Container>


      <Container size={'md'} mb={'xl'}>
        <Title>My Projects</Title>
        <Space h="xl" />

        <Projects/>
      </Container>
    </>
  )
}
