import Head from 'next/head'
import { Container, Grid, Title, Text, Box, Stack, Image, Group } from '@mantine/core'
import { SocialsComponent } from '@/components/social/socials'
import { Tooltip as ReactTooltip } from 'react-tooltip'
import { useEffect } from 'react';


export default function Home() {

  return (
    <>
      <Head>
        <title>jakub.app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container>
        <Grid align={'center'} justify={'center'} py={'xl'}>
          <Grid.Col span={6}>

            <Stack spacing={'sm'}>
              <Title>Jakub Szturomski</Title>

              <Text>Hi there 👋🏼 I’m Jakub, I’m <Text underline component='span'>21</Text> years old</Text>
              <Text>self-taught software engineer and cybersec enthusiastic</Text>

              <Group spacing={'sm'}>
              <SocialsComponent />
              </Group>
            </Stack>
          </Grid.Col>
          <Grid.Col span={6}>

          <Image
          width={300}
        radius="xl"
        src="avatar.jpg"
        alt="Random unsplash image"
      />
          </Grid.Col>
        </Grid>
      </Container>
    </>
  )
}
